Get Started Walkthrough for vscode knative [WIP]
redhat-developer/vscode-knative pull request #276
Opened 2022-08-04 11:28 UTC by sudhirverma

Fix: #262

2022-08-05 08:22 UTC, lstocchi reviewed
By a quick glance it looks good. I would change something in the descriptions but i'll leave the english review to Mohit as i suck.
Only 3 notes: 
1) maybe it's better to add an action in the `create new function` step that opens up the wizard to create a func. In IJ i cannot do it as the plugin works with all Jetbrains IDEs (IJ, GoLand, Pycharm,...) and they work differently but in vscode i guess it should be easier. 
2) Is it really necessary to have the add/remove env variable/volumes explained? 
3) in the invoke step i would mention the function need to be run before to invoke it.

2022-08-05 09:16 UTC, sudhirverma commented
> 2\. Is it really necessary to have the add/remove env variable/volumes explained?

@mohitsuman should we include the add/remove env variable/volumes in getting started or should I skip it?

2022-10-08 14:27 UTC, mohitsuman requested changes

2022-10-08 14:27 UTC, mohitsuman commented on package.json
> +            "description": "Deploy your function to your cluster directly from your IDE.\nOnly a function which has the source code opened in the IDE can be pushed. Right click on the function you wa
```suggestion
            "description": "Deploys a function to the currently configured Knative-enabled cluster from your IDE.\nOnly a function which has the source code opened in the IDE can be pushed. Right-click on the function you want to deploy (look for its node in the Functions tree), open the context menu (right-click on the node) and click on \"Deploy\". The Output Channel will show up with the deploy command where you can see the logs.",
```

2022-10-08 14:27 UTC, mohitsuman commented on package.json
> +            "title": "Deploy function",
```suggestion
            "title": "Deploy the Function",
```

2022-10-08 14:27 UTC, mohitsuman commented on package.json
> +            "description": "Invokes the Function by sending a request to the current running Function instance, either locally or remote.\nOnly a function which has the source code opened in the IDE
```suggestion
            "description": "Invokes the function by sending a test request to the currently running function instance, either locally or remote.\nOnly a function which has the source code opened in the IDE can be invoked. Right-click on the function you want to invoke (look for its node in the Functions tree), open the context menu (right-click on the node) and click on \"Invoke\". Provide all necessary details and click on Invoke.",
```

2022-10-08 14:27 UTC, mohitsuman commented on package.json
> +            "description": "Only a function which has the source code opened in the IDE can be configure to add environment variables.\n Right click on the function you want to add environment variab
```suggestion
            "description": "Only a function which has the source code opened in the IDE can be configured to add environment variables.\n Right-click on the function you want to add environment variables (look for its node in the Functions tree), open the context menu (right-click on the node) and click on \" Add Config\" and then click on \" Add Environment Variables\". An Interactive prompt will open in the terminal to add Environment variables.",
```

2022-10-08 14:27 UTC, mohitsuman commented on package.json
> +            "description": "Only a function which has the source code opened in the IDE can be configure to add volumes.\n Right click on the function you want to add volume (look for its node in the
```suggestion
            "description": "Only a function which has the source code opened in the IDE can be configured to add volumes.\n Right-click on the function you want to add volume (look for its node in the Functions tree), open the context menu (right-click on the node) and click on \" Add Config\" and then click on \" Add volumes\". An Interactive prompt will open in the terminal to add Secrets and ConfigMaps as Volume.",
```

2022-10-08 14:27 UTC, mohitsuman commented on package.json
> +            "description": "Only a function which has the source code opened in the IDE can be configure to remove environment variables.\n Right click on the function you want to remove environment
```suggestion
            "description": "Only a function which has the source code opened in the IDE can be configured to remove environment variables.\n Right-click on the function you want to remove environment variables (look for its node in the Functions tree), open the context menu (right-click on the node) and click on \"Remove Config\" and then click on \"Remove Environment Variables\". An Interactive prompt will open in the terminal to remove environment variables.",
```

2022-10-08 14:27 UTC, mohitsuman commented on package.json
> +            "description": "Only a function which has the source code opened in the IDE can be configure to remove volumes.\n Right click on the function you want to remove volume (look for its node
```suggestion
            "description": "Only a function which has the source code opened in the IDE can be configured to remove volumes.\n Right-click on the function you want to remove volume (look for its node in the Functions tree), open the context menu (right-click on the node) and click on \"Remove Config\" and then click on \"Remove volumes\". An Interactive prompt will open in the terminal to remove volume mounts from the function.",
```

2022-10-10 09:35 UTC, mohitsuman approved these changes

2022-10-10 12:28 UTC, merged